version: "3.8"

services:
  db:
    platform: linux/amd64
    image: public.ecr.aws/bitnami/postgresql:14
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
